### ISSUE TITLE
Uploading local files to S3

### ISSUE THREAD

**Issue by BabuinGH** [filestack/filestack-android#118]
I am trying to upload local video files from Android App to S3 bucket. As per github documentation for Filepicker.uploadLocalFile API,  path can be set for local file url. However, not sure of setting the parameters like the S3 location to save the file, policy & signature. 
After successfully uploading to S3 location, on response I would need Filepicker blob to save it to the backend.
Can someone help with an example to implement it correctly?

**Comment by BabuinGH** [comment]
@janhudzik could you help with this?

**Comment by shawnmaten** [comment]
Unfortunately the uploadLocalFile method doesn't allow you to set upload options like you can with the UI method. As for getting back a "Filepicker blob", you can pass in a FilepickerCallback to your call to uploadLocalFile and get back the info in a FPFile. There's an example of that in the README.

**Comment by kuraneabhijit** [comment]
Hi @shawnmaten ,
Did not understood your reply for @BabuinGH .
"Unfortunately the uploadLocalFile method doesn't allow you to set upload options like you can with the UI method"
Do we have any UI method where we can accomplish this. 
Actually I have the same question.
Can we upload the file to S3 , if we can then do we have any callback where we will get the upload progress  so that we can show the progress percentage to the user.
Currently I'm using Filepicker.uploadLocalFile to upload the files.
Please guide for this.

--
Thanks,
Abhijit

**Comment by AbhijitKurane** [comment]
Hi @shawnmaten ,
Actually I have the same question.
Can we upload the file to S3 (or set path), if we can then do we have any callback where we will get the upload progress  so that we can show the progress percentage to the user.
Currently I'm using Filepicker.uploadLocalFile to upload the files.
Looks like it has been added as milestone for 5.0.0 release.
But can you let us know by when this release is expected to be done in future.
Please guide for this.

--
Thanks,
Abhijit

**Comment by jkrzemie** [comment]
Hi,
When will this issue be resolved ? It's a blocker for our android app as we cannot set specific parameters (that we can do on iOS). 

Best
Jacob

**Comment by shawnmaten** [comment]
@jkrzemie I've completed most of the work for our [new Java SDK](https://github.com/filestack/filestack-java) and will be moving on to this library soon. Do you only need local file uploads? If so the Java SDK might suit your needs.

**Comment by shawnmaten** [comment]
This is available in v2.
